# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://aiot-group.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: AIoT Lab
# Description of the Site
description: Cutting-Edge Research on Artificial Intelligence of Things
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /img/LogoAIoT413x367.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /img/backgroundhome1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aiot@phenikaa-uni.edu.vn
facebook_username: aiot.lab
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  Pham Ngoc Viet
phone_number: 0362851201
add_room: A6-401, Phenikaa University
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
address: "Yen nghia, Ha Dong, Ha Noi, Viet Nam"
name_faculty: Faculty of Computer Science

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: AIoT
# URL for the Image of the Author
author-image: /img/aiot_logo_thiep.png
# 60 Words About the Author
author-about: We are part of Faculty of Computer Science, Phenikaa University
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AIoT-Group

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: "projects/:title"

include:
  - _pages

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
