# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://aiot-group.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: AIoT Lab
# Description of the Site
description: Cutting-Edge Research on Artificial Intelligence of Things
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://scontent.fhan19-1.fna.fbcdn.net/v/t1.15752-9/292714853_1938639683192584_6662020547836813844_n.png?_nc_cat=100&ccb=1-7&_nc_sid=ae9488&_nc_ohc=WdsZLDCFwkwAX9oP8Ra&tn=CBgCmg6DpGWz-opu&_nc_ht=scontent.fhan19-1.fna&oh=03_AVIZyTl4qlR5MiortOofmIjC0-EG65g7k2w16NfTUeqSSg&oe=63118806

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://scontent.fhan14-1.fna.fbcdn.net/v/t1.15752-9/291786643_1271009350361600_1191903467666023132_n.png?_nc_cat=110&ccb=1-7&_nc_sid=ae9488&_nc_ohc=zxYDEoqwVD4AX92QQ6T&_nc_ht=scontent.fhan14-1.fna&oh=03_AVL83nZTejPE2AEV_6et6cTDpr139-A3un-J-YHQNiXzZQ&oe=63168D11

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aiot@phenikaa-uni.edu.vn
facebook_username: aiot.lab
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  AIoT-Group
phone_number: 03..569874
add_room: A6-401, Phenikaa University
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
address: "Yen nghia, Ha Dong, Ha Noi, Viet Nam"
name_faculty: Faculty of Computer Science

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: aiot

# Name of the Author
author-name: AIoT
# URL for the Image of the Author
author-image: https://scontent.fhan19-1.fna.fbcdn.net/v/t1.15752-9/292714853_1938639683192584_6662020547836813844_n.png?_nc_cat=100&ccb=1-7&_nc_sid=ae9488&_nc_ohc=HjpEIucuLOcAX-8wMbt&tn=CBgCmg6DpGWz-opu&_nc_ht=scontent.fhan19-1.fna&oh=03_AVKQ88zgclOL5OeXftUgL3LepQfKKJjo_KZe8Gf9xACgow&oe=6305AA86
# 60 Words About the Author
author-about: We are part of Faculty of Computer Science, Phenikaa University
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AIoT-Group

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: "projects/:title"

include:
  - _pages

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
